import Providers from '@/utils/providers';
import PageContainer from '@/components/base/PageContainer';

import '../styles/reset.css';
import '../styles/reset.css';

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="ru">
            <body>
                <Providers>
                    <PageContainer>{children}</PageContainer>
                </Providers>
            </body>
        </html>
    );
}

